<!DOCTYPE html>
<html>
<head>
<title><?php if ($pagetitle): echo $pagetitle . ' | '; endif; ?><?php echo $title; ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $basepath; ?>/asset/css/normalize.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $basepath; ?>/asset/css/common.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $basepath; ?>/asset/css/skin.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $basepath; ?>/asset/js/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>/asset/js/inbox.js"></script>
</head>
<body>
<nav id="nav" role="navigation">
  <ul class="nav-right">
    <li><a href="/settings">Preferences</a></li>
    <li><a href="/inbox">Inbox</a></li>
    <li><a href="/">Home</a></li>
  </ul>
</nav>
<div id="main">
<?php echo $content; ?>
<div id="main">
</body>
</html>