<!-- Main inbox template: this where things gets complicated. -->
<div id="folders" class="inverse loading">
  <div class="content">
    <ul id="special-folders">
      <li class="special folder-starred">
        Starred
      </li>
      <li class="special folder-search">
        Search
      </li>
    </ul>
    <ul id="all-folders">
      <li class="folder folder-remote">Folders<ul class="children"></ul></li>
    </ul>
  </div>
</div>
<div id="views">
  <div id="viewpane">
    <div id="thread-view">
      <div class="header">
        <div class="title">
          Expanded discussion
          <a class="close" href="#" title="Close view">Close</a>
        </div>
      </div>
      <div class="reply-form">
        <form id="reply-form">
          <textarea name="body"></textarea>
          <br/>
          <div class="actions">
            <input type="submit" value="Send"/>
          </div>
          <div class="clear"></div>
        </form>
      </div>
      <div class="content"></div>
    </div>
  </div>
  <div id="inbox" class="loading">
    <div class="content">
      <!-- Current folder thread list! -->
    </div>
  </div>
  <div class="clear"></div>
</div>