<!-- Main inbox template: this where things gets complicated. -->
<div id="folders" class="inverse loading">
  <div class="content">
    <ul id="special-folders">
      <li class="special folder-starred">
        Starred
      </li>
      <li class="special folder-search">
        Search
      </li>
    </ul>
    <ul id="all-folders">
      <li class="folder">Folders<ul class="children"></ul></li>
    </ul>
  </div>
</div>
<div id="views">
  <div id="viewpane">
    <div id="compose">
      <form id="compose-form">
        <label for="to">To</label>
        <input name="to" type="text"/>
        <br/>
        <label for="cc">CC</label>
        <input name="cc" type="text"/>
        <br/>
        <label for="bcc">BCC</label>
        <input name="bcc" type="text"/>
        <br/>
        <textarea name="body"></textarea>
        <br/>
        <input type="submit" value="Send"/>
      </form>
    </div>
    <div id="thread-view">
      <div class="content"></div>
      <hr/>
      <form id="reply-form">
        <textarea name="body"></textarea>
        <br/>
        <input type="submit" value="Send"/>
      </form>
    </div>
  </div>
  <div id="inbox" class="loading">
    <div class="content">
      <!-- Current folder thread list! -->
    </div>
  </div>
  <div class="clear"></div>
</div>
