<!DOCTYPE html>
<html>
<head>
<title><?php if ($pagetitle): echo $pagetitle . ' | '; endif; ?><?php echo $title; ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $basepath; ?>asset/css/normalize.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $basepath; ?>asset/css/common.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $basepath; ?>asset/css/skin.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/mustache-0.7.3.min.js"></script>
<!-- Devel mode, later aggregate it -->
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/template.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/dispatcher.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/folder.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/thread.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/view.js"></script>
<script type="text/javascript" src="<?php echo $basepath; ?>asset/js/inbox/main.js"></script>
</head>
<body>
<nav id="nav" role="navigation">
  <span class="brand nav-left">
    <a><?php echo $title; ?></a>
  </span>
  <ul class="nav-right">
    <?php if ($isAuthenticated): ?>
    <li><a href="/app/logout">Logout</a></li>
    <li><a href="/app/settings">Preferences</a></li>
    <li><a href="/app/inbox">Inbox</a></li>
    <?php endif; ?>
  </ul>
</nav>
<div id="main">
<?php echo $content; ?>
</div>
</body>
</html>